version: '3.8'

services:
  help-scout-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: help-scout-mcp-server:latest
    container_name: help-scout-mcp-server
    env_file: .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - helpscout-network

  # Optional: Redis for distributed caching (commented out by default)
  # redis:
  #   image: redis:7-alpine
  #   container_name: helpscout-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - helpscout-network

networks:
  helpscout-network:
    driver: bridge

# volumes:
#   redis_data: